In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as mlt
import os 
import sys

In [5]:
file_paths = {
    "max_temperature": "data/_2017/_attributes/max_temperature.csv",
    "mean_temperature": "data/_2017/_attributes/mean_temperature.csv",
    "max_precipitation": "data/_2017/_attributes/max_precipitation.csv",
    "mean_precipitation": "data/_2017/_attributes/mean_precipitation.csv",
    "mslp": "data/_2017/_attributes/mslp.csv",
}

# Initialize an empty list to store DataFrames
dfs = []

# Read each CSV and extract relevant columns
for name, path in file_paths.items():
    df = pd.read_csv(path)
    # Identify unique columns (excluding common ones)
    unique_cols = [col for col in df.columns if col not in ['valid_time', 'latitude', 'longitude']]
    if unique_cols:
        unique_col = unique_cols[0]  # Assuming one unique column per file
        df = df[['valid_time', 'latitude', 'longitude', unique_col]]
        df.rename(columns={unique_col: name}, inplace=True)  # Rename to file-specific name
        dfs.append(df)

# Merge all DataFrames on common columns
merged_df = dfs[0]
for df in dfs[1:]:
    merged_df = pd.merge(merged_df, df, on=['valid_time', 'latitude', 'longitude'], how='outer')

# Save to a new CSV file
if os.path.exists("data/_2017/_merged/merged_data.csv"):
    print("File alreay exists")
else:
    merged_df.to_csv("data/_2017/_merged/merged_data.csv", index=False)
    print("File created")

# Display the merged DataFrame head

File created

In [6]:
df = pd.read_csv("data\_2017\_merged\merged_data.csv")
df

<>:1: SyntaxWarning: invalid escape sequence '\_'
<>:1: SyntaxWarning: invalid escape sequence '\_'
C:\Users\david\AppData\Local\Temp\ipykernel_21032\2826708176.py:1: SyntaxWarning: invalid escape sequence '\_'
  df = pd.read_csv("data\_2017\_merged\merged_data.csv")

,valid_time,latitude,longitude,max_temperature,mean_temperature,max_precipitation,mean_precipitation,mslp
0,2017-01-01,18.80,72.8,299.98834,297.88855,0.0,0.0,101286.914
1,2017-01-01,19.05,72.8,300.50903,297.68063,0.0,0.0,101289.340
2,2017-01-02,18.80,72.8,300.18155,297.97018,0.0,0.0,101376.470
3,2017-01-02,19.05,72.8,300.59710,297.71616,0.0,0.0,101381.940
4,2017-01-03,18.80,72.8,300.84050,298.17783,0.0,0.0,101383.600
...,...,...,...,...,...,...,...,...
725,2017-12-29,19.05,72.8,300.63342,297.56918,0.0,0.0,101280.180
726,2017-12-30,18.80,72.8,299.42502,297.32553,0.0,0.0,101288.195
727,2017-12-30,19.05,72.8,299.96167,297.15420,0.0,0.0,101289.760
728,2017-12-31,18.80,72.8,298.98633,297.17830,0.0,0.0,101170.150
729,2017-12-31,19.05,72.8,299.74506,297.04105,0.0,0.0,101172.540