In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as mlt
import os 
import sys

In [2]:
file_paths = {
    "max_temperature": "data/_2015/_attributes/max_temperature.csv",
    "mean_temperature": "data/_2015/_attributes/mean_temperature.csv",
    "max_precipitation": "data/_2015/_attributes/max_precipitation.csv",
    "mean_precipitation": "data/_2015/_attributes/mean_precipitation.csv",
    "mslp": "data/_2015/_attributes/mslp.csv",
}

# Initialize an empty list to store DataFrames
dfs = []

# Read each CSV and extract relevant columns
for name, path in file_paths.items():
    df = pd.read_csv(path)
    # Identify unique columns (excluding common ones)
    unique_cols = [col for col in df.columns if col not in ['valid_time', 'latitude', 'longitude']]
    if unique_cols:
        unique_col = unique_cols[0]  # Assuming one unique column per file
        df = df[['valid_time', 'latitude', 'longitude', unique_col]]
        df.rename(columns={unique_col: name}, inplace=True)  # Rename to file-specific name
        dfs.append(df)

# Merge all DataFrames on common columns
merged_df = dfs[0]
for df in dfs[1:]:
    merged_df = pd.merge(merged_df, df, on=['valid_time', 'latitude', 'longitude'], how='outer')

# Save to a new CSV file
if os.path.exists("data/_2015/_merged/merged_data.csv"):
    print("File alreay exists")
else:
    merged_df.to_csv("data/_2015/_merged/merged_data.csv", index=False)
    print("File created")

# Display the merged DataFrame head

File created

In [3]:
df = pd.read_csv("data\_2015\_merged\merged_data.csv")
df

<>:1: SyntaxWarning: invalid escape sequence '\_'
<>:1: SyntaxWarning: invalid escape sequence '\_'
C:\Users\david\AppData\Local\Temp\ipykernel_31772\504059257.py:1: SyntaxWarning: invalid escape sequence '\_'
  df = pd.read_csv("data\_2015\_merged\merged_data.csv")

,valid_time,latitude,longitude,max_temperature,mean_temperature,max_precipitation,mean_precipitation,mslp
0,2015-01-01,18.80,72.8,297.28986,296.37503,6.628243e-05,8.249449e-06,100941.98
1,2015-01-01,19.05,72.8,297.46942,296.16470,5.730815e-05,6.722319e-06,100941.74
2,2015-01-02,18.80,72.8,297.12677,296.18990,4.006550e-06,6.834957e-07,101190.31
3,2015-01-02,19.05,72.8,297.52744,296.07968,3.242760e-06,2.185656e-07,101190.35
4,2015-01-03,18.80,72.8,298.04413,296.54760,6.676777e-07,2.781991e-08,101373.72
...,...,...,...,...,...,...,...,...
725,2015-12-29,19.05,72.8,302.66080,298.41630,0.000000e+00,0.000000e+00,101580.26
726,2015-12-30,18.80,72.8,302.85120,299.10422,1.430884e-05,5.962017e-07,101399.90
727,2015-12-30,19.05,72.8,303.61963,298.72757,0.000000e+00,0.000000e+00,101405.84
728,2015-12-31,18.80,72.8,302.69116,299.34232,0.000000e+00,0.000000e+00,101452.75
729,2015-12-31,19.05,72.8,303.42590,298.98570,0.000000e+00,0.000000e+00,101462.01